# -*- coding: utf-8 -*-
"""covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_K7hNGhqstCEts5y9-t0FigCKzDs9nn5
"""

## Covid-19 data analysis on month on month(Confirmed,deaths , recovered cases count)
## Data has been taken from Kaggle.com
# Running the code using Google colab 
import pandas as pd
import numpy as np
import seaborn as sns

from google.colab import files
uploaded = files.upload()

import io
df=pd.read_csv(io.BytesIO(uploaded['covid_19_data.csv']))

df.head()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline 
df.describe()

sns.heatmap(df.corr())

sns.lineplot(x='ObservationDate',y='Confirmed',data=df)

type(df['ObservationDate'])

df['Date']=pd.to_datetime(df['ObservationDate'])

df['Month']=df['Date'].apply(lambda Date:Date.month)

df.head()

df['Year']=df['Date'].apply(lambda Date:Date.year)

df.head()

sns.lineplot(x='Month',y='Confirmed',data=df)

sns.lineplot(x='Month',y='Deaths',data=df)

sns.lineplot(x='Month',y='Recovered',data=df)

df.drop('ObservationDate',axis=1)

df['Country/Region'].value_counts()

